
 ##############################################################################
 #                                asparagus                                   #
 #                                                                            #
 #    Copyright (C) 2014  Andreas Grapentin                                   #
 #                                                                            #
 #    This program is free software: you can redistribute it and/or modify    #
 #    it under the terms of the GNU General Public License as published by    #
 #    the Free Software Foundation, either version 3 of the License, or       #
 #    (at your option) any later version.                                     #
 #                                                                            #
 #    This program is distributed in the hope that it will be useful,         #
 #    but WITHOUT ANY WARRANTY; without even the implied warranty of          #
 #    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           #
 #    GNU General Public License for more details.                            #
 #                                                                            #
 #    You should have received a copy of the GNU General Public License       #
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.   #
 ##############################################################################

 # This is the asparagus testing framework backend TCL script.
 ##############################################################################

# include utility modules
source [file dirname [info script]]/lib/feedback.tcl
source [file dirname [info script]]/lib/string.tcl
source [file dirname [info script]]/lib/globals.tcl

# include the step dispatcher
source [file dirname [info script]]/steps/dispatcher.tcl

# include custom steps
source [file dirname [info script]]/steps/custom.tcl

# include the default step definitions
source [file dirname [info script]]/steps/default.tcl

# add your custom step definitions here, or add them to a dedicated file
# and source this file here. Also take a look at steps/default.tcl for further
# reference on step implementation.

### example step definition:
# proc when_something_happens { args } {
#
#   ## describe what your step does in TCL
#   ## use `fail_step ?msg?` to describe failure states
#
#   ## end your step with a `pass_step`
#   pass_step
# }
### register your step
# asparagus_register_step when_something_happens "when something happens"
#
### now you can use you step in your tests
# given an executable "test"
#   when something happens
#   then ...
